--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/VErrorHandler
build-by-default: true
branches:
- main
projects:
  VErrorHandler:
    path: ""
    model: virion
    type: library
...
